# Site
name: "ITSSL"
title: "Information Technology Society of Sri Lanka"
description: "Information Technology Society of Sri Lanka"
logo: 'assets/images/logo.svg'
favicon: 'assets/images/logo.png'
baseurl: /itssl.org
google_analytics: ''
disqus: ''
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/
email: contact@itssl.org


# Plugins
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives


# Social
social:
  instagram: https://www.instagram.com/skiddow/
  facebook: https://www.facebook.com/skiddow
  twitter: https://twitter.com/skiddow_tw
