title: "Information Technology Society of Sri Lanka"
email: contact@itssl.org
formspree: mjvjwbrv
timezone: UTC
baseurl: "/itssl.org"
permalink: "/:title/"
logo: 'assets/images/itssl-logo.jpg'
favicon: 'assets/images/favicon.ico'
author: Admin
paginate: 30
disqus: 'demowebsite'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1


# Social
social:
#  instagram: https://www.instagram.com/itssl/
  facebook: https://www.facebook.com/itsslorg
  twitter: https://twitter.com/itsslorg
  youtube: https://www.youtube.com/channel/UC_pqx2Kr184Kf6DSN7TIpWg

# Plugins
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
